<?php

return array (
  'CMDR-NAT-DRD-S' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'NAT GATEWAY (Small)',
    'measurement_unit' => 'Unit',
    'description' => 'NAT GATEWAY (Small)',
    'price_per_unit' => 15.5925,
    'rate_card_price_per_unit' => 29.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-EIP-SHR-DAY' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Network (DR Elastic IP)',
    'measurement_unit' => 'Unit',
    'description' => '(Per Day) DR Elastic IP',
    'price_per_unit' => 21.945,
    'rate_card_price_per_unit' => 41.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 428.4,
    'rate_card_price_per_unit' => 897.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-NAT-SHR-XL' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'NAT Gateway (Extra-Large)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 461.475,
    'rate_card_price_per_unit' => 966.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CPFS-PFS-MDY-3OTC' => 
  array (
    'category_name' => 'Cloud Professional Services',
    'category_code' => 'CPFS',
    'name' => 'Manday - =>3 Days',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 682.5,
    'rate_card_price_per_unit' => 1430.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CLIC-HBDR10-NOD' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Agent (>10 pair agent)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 57.12,
    'rate_card_price_per_unit' => 119.68,
    'transfer_price_per_unit' => 0.5,
  ),
  'CMPT-ECS-SHR-M3.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 2654.4,
    'rate_card_price_per_unit' => 5561.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 206.976,
    'rate_card_price_per_unit' => 433.66,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-EIP-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Elastic IP',
    'measurement_unit' => 'Unit Per Day',
    'description' => '',
    'price_per_unit' => 0.525,
    'rate_card_price_per_unit' => 1.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-30' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (11-30Mbps )+ AntiDDoS + 4 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 25.2,
    'rate_card_price_per_unit' => 52.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.6XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.6xlarge.dr',
    'measurement_unit' => ' Unit ',
    'description' => '',
    'price_per_unit' => 95.361,
    'rate_card_price_per_unit' => 199.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-80' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (51-80Mbps) + 8 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 12.075,
    'rate_card_price_per_unit' => 25.3,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-EVS-SHR1000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR EVS Storage - 1,000GB',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.1103,
    'rate_card_price_per_unit' => 0.23,
    'transfer_price_per_unit' => 0.5,
  ),
  'CNET-BWS-SHR-100' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Shared Bandwidth + 1 EIP (100Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 67.2,
    'rate_card_price_per_unit' => 140.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'SECT-VAS-EIP-STD' => 
  array (
    'category_name' => 'Security Services',
    'category_code' => 'SECT',
    'name' => 'Cloud Vulnerability Assessment (Per IP)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 42.0,
    'rate_card_price_per_unit' => 88.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMDR-NAT-DRD-M' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'NAT GATEWAY (Medium)',
    'measurement_unit' => 'Unit',
    'description' => 'NAT GATEWAY (Medium)',
    'price_per_unit' => 22.5225,
    'rate_card_price_per_unit' => 42.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-DDH-DDT-R3P.46XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.46xlarge.ddh',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 11534.4075,
    'rate_card_price_per_unit' => 24167.33,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 10.7205,
    'rate_card_price_per_unit' => 22.46,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SQLENT' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft SQL (Enterprise) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1571.4143,
    'rate_card_price_per_unit' => 3292.49,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-NAT-XLSHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'NAT Gateway (Extra-Large)',
    'measurement_unit' => 'Unit',
    'description' => 'Public NAT gateways translate private IP addresses into EIPs, and are used by cloud servers in a VPC for secure, cost-effective Internet access. Private NAT gateways translate between private IP addresses, and are used between VPCs or your VPC and on-premises data center to keep legacy networks running after cloud migration. Maximum SNAT Connections = 1,000,000; Bandwidth=20Gbps; PPS=2,000,000',
    'price_per_unit' => 28.5,
    'rate_card_price_per_unit' => 31.35,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMNS-MBR-NOD-STD' => 
  array (
    'category_name' => 'Cloud Managed Service',
    'category_code' => 'CMNS',
    'name' => 'Managed Backup and Restore',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 31.5,
    'rate_card_price_per_unit' => 66.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1570.8,
    'rate_card_price_per_unit' => 3291.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-MPDR-NOD-HBDR1' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Agent (per pair agent)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 67.2,
    'rate_card_price_per_unit' => 140.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.LARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.large',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 141.75,
    'rate_card_price_per_unit' => 297.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMNS-MDR-NOD-STD' => 
  array (
    'category_name' => 'Cloud Managed Service',
    'category_code' => 'CMNS',
    'name' => 'Managed DR',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 26.25,
    'rate_card_price_per_unit' => 55.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 856.8,
    'rate_card_price_per_unit' => 1795.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLWEB' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft SQL (Web) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 2.625,
    'rate_card_price_per_unit' => 5.5,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 26.2448,
    'rate_card_price_per_unit' => 54.99,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 21.441,
    'rate_card_price_per_unit' => 44.92,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-VFW-DDT-FGDAY' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Additional Services-Security (DR Cloud Firewall Fortigate)',
    'measurement_unit' => 'Unit',
    'description' => '(Per Day) DR Cloud Firewall Fortigate',
    'price_per_unit' => 2.31,
    'rate_card_price_per_unit' => 4.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SRVSTDOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft Windows Server (Core Pack) - Standard',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 14.0595,
    'rate_card_price_per_unit' => 29.46,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-DRCOR-8OTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- RHEL (1-8vCPU)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 28.791,
    'rate_card_price_per_unit' => 60.32,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-30' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (11-30Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 12.3375,
    'rate_card_price_per_unit' => 25.85,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 254.289,
    'rate_card_price_per_unit' => 532.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-COR-8' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'RHEL (1-8vCPU)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 28.791,
    'rate_card_price_per_unit' => 60.32,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-EVS-SHR5000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR EVS Storage - 5,000GB',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.105,
    'rate_card_price_per_unit' => 0.22,
    'transfer_price_per_unit' => 0.5,
  ),
  'CMPT-ECS-SHP-M3P.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1100.4,
    'rate_card_price_per_unit' => 2305.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 214.2,
    'rate_card_price_per_unit' => 448.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 51.744,
    'rate_card_price_per_unit' => 108.42,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMDR-ELB-DRD-STD' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Elastic Load Balancer',
    'measurement_unit' => 'Unit',
    'description' => 'Elastic Load Balancer',
    'price_per_unit' => 32.9175,
    'rate_card_price_per_unit' => 62.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 12.936,
    'rate_card_price_per_unit' => 27.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-100DR' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Cloud Server Disaster Recovery (vPLL)',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 9.975,
    'rate_card_price_per_unit' => 20.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 103.488,
    'rate_card_price_per_unit' => 216.83,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 46.5728,
    'rate_card_price_per_unit' => 97.58,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 31.7888,
    'rate_card_price_per_unit' => 66.61,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.12XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.12xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 314.9003,
    'rate_card_price_per_unit' => 659.79,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-MPDR-NOD-HBDR20' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Agent (>10 pair agent)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 57.12,
    'rate_card_price_per_unit' => 119.68,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-SFS-SHR-STD' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Scalable File Service (SFS)',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.2258,
    'rate_card_price_per_unit' => 0.47,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-80' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (51-80Mbps) + AntiDDoS + 8 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 20.475,
    'rate_card_price_per_unit' => 42.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.LARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.large.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 11.6445,
    'rate_card_price_per_unit' => 24.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SRVDC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft Windows Server (Core Pack) - Data Center',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 97.5713,
    'rate_card_price_per_unit' => 204.44,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 283.5,
    'rate_card_price_per_unit' => 594.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLENT' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft SQL (Enterprise) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 142.275,
    'rate_card_price_per_unit' => 298.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CMPT-ECS-C3.LARGE' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'MPDR Replication Proxy',
    'measurement_unit' => 'Unit',
    'description' => '-',
    'price_per_unit' => 53.55,
    'rate_card_price_per_unit' => 112.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 392.7,
    'rate_card_price_per_unit' => 822.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMNS-MOS-NOD-STD' => 
  array (
    'category_name' => 'Cloud Managed Service',
    'category_code' => 'CMNS',
    'name' => 'Managed Operating System',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 31.5,
    'rate_card_price_per_unit' => 66.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-OBS-SHR5000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR OBS Storage - 5,000GB',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0578,
    'rate_card_price_per_unit' => 0.12,
    'transfer_price_per_unit' => 0.5,
  ),
  'CMPT-ECS-SHR-M3.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 663.6,
    'rate_card_price_per_unit' => 1390.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-VFW-DDT-OSDAY' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Additional Services-Security (DR Cloud Firewall OPNSense)',
    'measurement_unit' => 'Unit',
    'description' => '(Per Day) DR Cloud Firewall OPNSense',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.LARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.large',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 53.55,
    'rate_card_price_per_unit' => 112.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CPFS-PFS-MDY-0.5OTC' => 
  array (
    'category_name' => 'Cloud Professional Services',
    'category_code' => 'CPFS',
    'name' => 'Manday - 0.5Days',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 420.0,
    'rate_card_price_per_unit' => 880.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMDR-NAT-DRD-XL' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'NAT GATEWAY (Extra-Large)',
    'measurement_unit' => 'Unit',
    'description' => 'NAT GATEWAY (Extra-Large)',
    'price_per_unit' => 1905.75,
    'rate_card_price_per_unit' => 3630.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-EVS-SHR-STD' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Elastic Volume Service (EVS)',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.1103,
    'rate_card_price_per_unit' => 0.23,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-50' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (31-50Mbps) + AntiDDoS + 6 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 22.05,
    'rate_card_price_per_unit' => 46.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-80' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (51-80Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 10.7625,
    'rate_card_price_per_unit' => 22.55,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-ELB-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'Elastic Load Balancer',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 3.675,
    'rate_card_price_per_unit' => 7.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-SEEDVM.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'Cold DR - Seeding VM',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 20.685,
    'rate_card_price_per_unit' => 43.34,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 107.1,
    'rate_card_price_per_unit' => 224.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-ELB-SHR-STD' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Elastic Load Balancer',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 61.425,
    'rate_card_price_per_unit' => 128.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3P.6XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.6xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1650.6,
    'rate_card_price_per_unit' => 3458.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.SMALL' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.small',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 26.775,
    'rate_card_price_per_unit' => 56.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 3460.8,
    'rate_card_price_per_unit' => 7251.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1919.925,
    'rate_card_price_per_unit' => 4022.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-RDSSAL' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft Remote Desktop Services (SAL)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 2.1,
    'rate_card_price_per_unit' => 4.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-RDSSALOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft Remote Desktop Services (SAL)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 18.459,
    'rate_card_price_per_unit' => 38.68,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1919.925,
    'rate_card_price_per_unit' => 2781.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-SHR-300' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Shared Bandwidth + 1 EIP (300Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 98.7,
    'rate_card_price_per_unit' => 206.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CMNS-MDR-NODDAY' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Cloud Server Disaster Recovery Managed Service - Per Day',
    'measurement_unit' => 'VM',
    'description' => '',
    'price_per_unit' => 5.25,
    'rate_card_price_per_unit' => 11.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1524.6,
    'rate_card_price_per_unit' => 3194.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMNS-MPT-NOD-STD' => 
  array (
    'category_name' => 'Cloud Managed Service',
    'category_code' => 'CMNS',
    'name' => 'Managed Patching',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 26.25,
    'rate_card_price_per_unit' => 55.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMON-TIS-NOD-STD' => 
  array (
    'category_name' => 'Cloud Monitoring',
    'category_code' => 'CMON',
    'name' => 'TCS inSight vMonitoring',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 21.0,
    'rate_card_price_per_unit' => 44.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.MICRO.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.micro.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 1.2968,
    'rate_card_price_per_unit' => 2.72,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CLIC-HBDR1-NOD' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Agent (per pair agent)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 67.2,
    'rate_card_price_per_unit' => 140.8,
    'transfer_price_per_unit' => 0.5,
  ),
  'CNET-EIP-SHR-FOC' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Included Elastic IP (FOC)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.12XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.12xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 4712.4,
    'rate_card_price_per_unit' => 9873.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-BWS-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Bandwidth',
    'measurement_unit' => 'Mbps Per Day',
    'description' => '',
    'price_per_unit' => 0.5775,
    'rate_card_price_per_unit' => 1.21,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-MM1000' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '3x Master Nodes (Cluster Size:201-1000)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1329.4575,
    'rate_card_price_per_unit' => 2785.53,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 3141.6,
    'rate_card_price_per_unit' => 6582.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLSTDOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft SQL (Standard) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 417.375,
    'rate_card_price_per_unit' => 874.5,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CLIC-CSDR-NOD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'Cloud Server Disaster Recovery Replication',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 14.7,
    'rate_card_price_per_unit' => 30.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-10' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (1-10Mbps) + 2 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 15.75,
    'rate_card_price_per_unit' => 33.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-MM50' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '3x Master Nodes (Cluster Size:1-50)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 373.1175,
    'rate_card_price_per_unit' => 781.77,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-NAT-SSHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'NAT Gateway (Small)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1.05,
    'rate_card_price_per_unit' => 2.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-SHR-DAY' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Network (DR Bandwidth)',
    'measurement_unit' => 'Mbps',
    'description' => '(Per Day) DR Bandwidth',
    'price_per_unit' => 1.0973,
    'rate_card_price_per_unit' => 2.09,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SQLWEB' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft SQL (Web) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 26.3655,
    'rate_card_price_per_unit' => 55.24,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.3XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.3xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 497.7,
    'rate_card_price_per_unit' => 1042.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-OBS-SHR-IMG' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Image Storage',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.063,
    'rate_card_price_per_unit' => 0.13,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-OBS-SHR-STD' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Object Storage Service (OBS)',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.063,
    'rate_card_price_per_unit' => 0.13,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 4401.6,
    'rate_card_price_per_unit' => 9222.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 550.2,
    'rate_card_price_per_unit' => 1152.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-SHR-DAY' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Network (DR Bandwidth + Anti-DDoS)',
    'measurement_unit' => 'Mbps',
    'description' => '(Per Day) DR Bandwidth + Anti-DDoS',
    'price_per_unit' => 0.5775,
    'rate_card_price_per_unit' => 1.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 171.4965,
    'rate_card_price_per_unit' => 359.33,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.LARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.large.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 6.468,
    'rate_card_price_per_unit' => 13.55,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMDR-NAT-DRD-L' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'NAT GATEWAY (Large)',
    'measurement_unit' => 'Unit',
    'description' => 'NAT GATEWAY (Large)',
    'price_per_unit' => 502.425,
    'rate_card_price_per_unit' => 957.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-NAT-MSHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'NAT Gateway (Medium)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 5.775,
    'rate_card_price_per_unit' => 12.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1730.4,
    'rate_card_price_per_unit' => 3625.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-EVS-SHR10000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR EVS Storage - 10,000GB',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.105,
    'rate_card_price_per_unit' => 0.21,
    'transfer_price_per_unit' => 0.5,
  ),
  'CDRV-CMPT-ECS-C3.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 7.7648,
    'rate_card_price_per_unit' => 16.27,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.6XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.6xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 995.4,
    'rate_card_price_per_unit' => 2085.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 372.561,
    'rate_card_price_per_unit' => 780.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLWEBOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft SQL (Web) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 26.3655,
    'rate_card_price_per_unit' => 55.24,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-MPDR-NOD-HBDR1OTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Agent (per pair agent)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 67.2,
    'rate_card_price_per_unit' => 140.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-DRCOR-127OTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- RHEL (9-127vCPU)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 21.6038,
    'rate_card_price_per_unit' => 45.27,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 127.1445,
    'rate_card_price_per_unit' => 266.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-30' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (11-30Mbps) + 4 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 14.7,
    'rate_card_price_per_unit' => 30.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-L2BR-SHR-EXT' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'L2BR instance',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 47.775,
    'rate_card_price_per_unit' => 100.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-DRCOR-8' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- RHEL (1-8vCPU)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 28.791,
    'rate_card_price_per_unit' => 60.32,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 31.0485,
    'rate_card_price_per_unit' => 65.05,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CSEC-VFW-DDTOSDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Cloud Firewall (OPNSense)',
    'measurement_unit' => 'Days',
    'description' => '',
    'price_per_unit' => 2.1,
    'rate_card_price_per_unit' => 4.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLENTOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft SQL (Enterprise) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1571.85,
    'rate_card_price_per_unit' => 3293.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.SMALL.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.small.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 1.9425,
    'rate_card_price_per_unit' => 4.07,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.3XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.3xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 47.6805,
    'rate_card_price_per_unit' => 99.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 4288.2,
    'rate_card_price_per_unit' => 8984.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-GLB-SHR-DOMAIN' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Global Server Load Balancer (GSLB)',
    'measurement_unit' => 'Unit',
    'description' => 'Global Server Load Balancer provided by TT dotcom In house to address load balancing across multiple regions. Calculated based on per domain, where each domain is limited to 1000QPS',
    'price_per_unit' => 52.5,
    'rate_card_price_per_unit' => 110.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 6283.2,
    'rate_card_price_per_unit' => 13164.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 52.4843,
    'rate_card_price_per_unit' => 109.97,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 15.5243,
    'rate_card_price_per_unit' => 32.53,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-COR-127' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'RHEL (9-127vCPU)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 21.6038,
    'rate_card_price_per_unit' => 45.27,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 104.9685,
    'rate_card_price_per_unit' => 219.93,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-EDR-NOD-STD' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Anti-Virus (Panda)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 5.25,
    'rate_card_price_per_unit' => 11.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.LARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.large',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 82.95,
    'rate_card_price_per_unit' => 173.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 785.4,
    'rate_card_price_per_unit' => 1645.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 419.8688,
    'rate_card_price_per_unit' => 879.73,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.3XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.3xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 38.808,
    'rate_card_price_per_unit' => 81.31,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-50' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (31-50Mbps) + 6 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 13.65,
    'rate_card_price_per_unit' => 28.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SQLSTD' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft SQL (Standard) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 421.428,
    'rate_card_price_per_unit' => 882.99,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1134.0,
    'rate_card_price_per_unit' => 2376.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CLIC-HBDR50-NOD' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Agent (>50 pair agent)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 48.552,
    'rate_card_price_per_unit' => 101.73,
    'transfer_price_per_unit' => 0.5,
  ),
  'CMPT-ECS-SHR-C3.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1713.6,
    'rate_card_price_per_unit' => 3590.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-SM200' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '1x Master Nodes (Cluster Size:51-200)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 230.6325,
    'rate_card_price_per_unit' => 483.23,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-NAT-SHR-L' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'NAT Gateway (Large)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 154.35,
    'rate_card_price_per_unit' => 323.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-100' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (81-100Mbps) + AntiDDoS + 8 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 16.8,
    'rate_card_price_per_unit' => 35.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-WAF-SHR-HA' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Cloud Shared WAF (Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 31.5,
    'rate_card_price_per_unit' => 66.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-OBS-SHR10000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR OBS Storage - 10,000GB',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0578,
    'rate_card_price_per_unit' => 0.12,
    'transfer_price_per_unit' => 0.5,
  ),
  'CSBS-STRG-BCK-STD' => 
  array (
    'category_name' => 'Cloud Backup',
    'category_code' => 'CSBS',
    'name' => 'Backup Disk',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.1048,
    'rate_card_price_per_unit' => 0.231,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 93.1403,
    'rate_card_price_per_unit' => 195.15,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-USR-RDSSAL' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft Remote Desktop Services (SAL)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 18.6375,
    'rate_card_price_per_unit' => 39.05,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 23.289,
    'rate_card_price_per_unit' => 48.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-OBS-SHR1000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR OBS Storage - 1,000GB',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.063,
    'rate_card_price_per_unit' => 0.13,
    'transfer_price_per_unit' => 0.5,
  ),
  'CDRV-CMPT-ECS-M3.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 25.872,
    'rate_card_price_per_unit' => 54.21,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-DGW-SHR-EXT' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Direct Connect Virtual Gateway',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 49.875,
    'rate_card_price_per_unit' => 104.5,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-STRG-EVS-SHRSTD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'Cloud Server Disaster Recovery Storage',
    'measurement_unit' => 'GB',
    'description' => '',
    'price_per_unit' => 0.1103,
    'rate_card_price_per_unit' => 0.23,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 42.8768,
    'rate_card_price_per_unit' => 89.84,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 331.8,
    'rate_card_price_per_unit' => 695.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-DRCOR-127' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- RHEL (9-127vCPU)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 21.6038,
    'rate_card_price_per_unit' => 45.27,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-STRG-EVS-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Elastic Volume Service (EVS)',
    'measurement_unit' => 'GB Per Day',
    'description' => '',
    'price_per_unit' => 0.0473,
    'rate_card_price_per_unit' => 0.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.MICRO' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.micro',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 19.425,
    'rate_card_price_per_unit' => 40.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-NAT-LSHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'NAT Gateway (Large)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 10.5,
    'rate_card_price_per_unit' => 22.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-SM1000' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '1x Master Nodes (Cluster Size:201-1000)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 443.1525,
    'rate_card_price_per_unit' => 928.51,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 15.897,
    'rate_card_price_per_unit' => 33.31,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SRVSTD' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft Windows Server (Core Pack) - Standard',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 14.196,
    'rate_card_price_per_unit' => 29.74,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 2200.8,
    'rate_card_price_per_unit' => 4611.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 432.6,
    'rate_card_price_per_unit' => 906.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 216.3,
    'rate_card_price_per_unit' => 453.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.3XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.3xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 825.3,
    'rate_card_price_per_unit' => 1729.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 2268.0,
    'rate_card_price_per_unit' => 4752.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-BWD-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Bandwidth + AntiDDoS ',
    'measurement_unit' => 'Mbps Per Day',
    'description' => '',
    'price_per_unit' => 0.9975,
    'rate_card_price_per_unit' => 2.09,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 2709.525,
    'rate_card_price_per_unit' => 5677.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CPFS-PFS-MDY-1OTC' => 
  array (
    'category_name' => 'Cloud Professional Services',
    'category_code' => 'CPFS',
    'name' => 'Manday - =>1 Day',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 787.5,
    'rate_card_price_per_unit' => 1650.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-MM200' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '3x Master Nodes (Cluster Size:51-200)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 691.8975,
    'rate_card_price_per_unit' => 1449.69,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-100' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (81-100Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 9.975,
    'rate_card_price_per_unit' => 20.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 62.097,
    'rate_card_price_per_unit' => 130.11,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 865.2,
    'rate_card_price_per_unit' => 1812.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 186.2805,
    'rate_card_price_per_unit' => 390.3,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-100' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (81-100Mbps) + 8 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 10.5,
    'rate_card_price_per_unit' => 22.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLSTD' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft SQL (Standard) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 37.8,
    'rate_card_price_per_unit' => 79.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.12XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.12xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 279.4208,
    'rate_card_price_per_unit' => 585.45,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSBS-STRG-BCK-CSBSF' => 
  array (
    'category_name' => 'Cloud Backup',
    'category_code' => 'CSBS',
    'name' => 'Cloud Server Backup Service - Full Backup Capacity',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.105,
    'rate_card_price_per_unit' => 0.22,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-EIP-SHR-STD' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Elastic IP',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 10.5,
    'rate_card_price_per_unit' => 22.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 275.1,
    'rate_card_price_per_unit' => 576.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-L2BR-SHR-INT' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'vPLL L2BR Instance',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 27.1688,
    'rate_card_price_per_unit' => 56.93,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSBS-STRG-BCK-CSBSI' => 
  array (
    'category_name' => 'Cloud Backup',
    'category_code' => 'CSBS',
    'name' => 'Cloud Server Backup Service - Incremental Backup Capacity',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.105,
    'rate_card_price_per_unit' => 0.22,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-NAT-SHR-M' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'NAT Gateway (Medium)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 77.7,
    'rate_card_price_per_unit' => 162.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 165.9,
    'rate_card_price_per_unit' => 347.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-VFW-DDT-OS' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Cloud Firewall (OPNSense)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 52.5,
    'rate_card_price_per_unit' => 110.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1327.2,
    'rate_card_price_per_unit' => 2780.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 63.5723,
    'rate_card_price_per_unit' => 133.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CPFS-PFS-MDY-5OTC' => 
  array (
    'category_name' => 'Cloud Professional Services',
    'category_code' => 'CPFS',
    'name' => 'Manday - =>5 Days',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 630.0,
    'rate_card_price_per_unit' => 1320.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.LARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.large.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 3.885,
    'rate_card_price_per_unit' => 8.14,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CLIC-HBDR1-NODOTC' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Agent (per pair agent) per Month',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 67.2,
    'rate_card_price_per_unit' => 140.8,
    'transfer_price_per_unit' => 0.5,
  ),
  'CSBS-STRG-BCK-REPS' => 
  array (
    'category_name' => 'Cloud Backup',
    'category_code' => 'CSBS',
    'name' => 'Cloud Server Replication Service - Retention Capacity',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.105,
    'rate_card_price_per_unit' => 0.22,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SRVDC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft Windows Server (Core Pack) - Data Center',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 97.5713,
    'rate_card_price_per_unit' => 204.44,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-SHR-500' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Shared Bandwidth + 1 EIP (500Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 135.45,
    'rate_card_price_per_unit' => 283.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SRVSTD' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft Windows Server (Core Pack) - Standard',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 1.575,
    'rate_card_price_per_unit' => 3.3,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CSEC-VFW-DDTFGDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Cloud Firewall (Fortigate)',
    'measurement_unit' => 'Days',
    'description' => '',
    'price_per_unit' => 19.95,
    'rate_card_price_per_unit' => 41.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 567.0,
    'rate_card_price_per_unit' => 1188.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-BCK-SHR-STD' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Snapshot Storage',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.105,
    'rate_card_price_per_unit' => 0.22,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SRVDCOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft Windows Server (Core Pack) - Data Center',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 97.5713,
    'rate_card_price_per_unit' => 204.44,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-50' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (31-50Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 11.55,
    'rate_card_price_per_unit' => 24.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-10' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (1-10Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 13.125,
    'rate_card_price_per_unit' => 27.5,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-NAT-SHR-S' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'NAT Gateway (Small)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 15.75,
    'rate_card_price_per_unit' => 33.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 209.937,
    'rate_card_price_per_unit' => 439.87,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.12XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.12xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 3402.0,
    'rate_card_price_per_unit' => 7128.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 4536.0,
    'rate_card_price_per_unit' => 9504.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-VFW-DDT-FG' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Cloud Firewall (Fortigate)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 498.75,
    'rate_card_price_per_unit' => 1045.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 85.7483,
    'rate_card_price_per_unit' => 179.66,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-SM50' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '1x Master Nodes (Cluster Size:1-50)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 124.3725,
    'rate_card_price_per_unit' => 260.59,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 124.1888,
    'rate_card_price_per_unit' => 260.21,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-10' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (1-10Mbps) + AntiDDoS + 2 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 26.25,
    'rate_card_price_per_unit' => 55.0,
    'transfer_price_per_unit' => 0.0,
  ),
  '_catalog' => 
  array (
    'id' => '01993bbf-5ca7-708b-97aa-4f0cce8d7a14',
    'version_code' => 'v1.1.1',
    'version_name' => 'v1.1.1',
    'effective_from' => '2025-09-12',
    'effective_to' => NULL,
    'is_current' => true,
    'generated_at' => '2025-09-18 10:40:15',
  ),
);
