<?php

return array (
  'CDRV-CMPT-ECS-C3.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 14.79,
    'rate_card_price_per_unit' => 16.27,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 20.42,
    'rate_card_price_per_unit' => 22.46,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 6592.0,
    'rate_card_price_per_unit' => 7251.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 709.64,
    'rate_card_price_per_unit' => 780.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-MM50' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '3x Master Nodes (Cluster Size:1-50)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 710.7,
    'rate_card_price_per_unit' => 781.77,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 30.28,
    'rate_card_price_per_unit' => 33.31,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 408.0,
    'rate_card_price_per_unit' => 448.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 49.28,
    'rate_card_price_per_unit' => 54.21,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-STRG-EVS-SHRSTD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'Cloud Server Disaster Recovery Storage',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.21,
    'rate_card_price_per_unit' => 0.23,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-30' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (11-30Mbps) + 4 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 28.0,
    'rate_card_price_per_unit' => 30.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 163.33,
    'rate_card_price_per_unit' => 179.66,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 3296.0,
    'rate_card_price_per_unit' => 3625.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-OBS-SHR10000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR OBS Storage - 10,000GB',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.11,
    'rate_card_price_per_unit' => 0.12,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.12XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.12xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 6480.0,
    'rate_card_price_per_unit' => 7128.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-NAT-SHR-S' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'NAT Gateway (Small)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 30.0,
    'rate_card_price_per_unit' => 33.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3P.6XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.6xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 3144.0,
    'rate_card_price_per_unit' => 3458.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-RDSSAL' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft Remote Desktop Services (SAL)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 4.0,
    'rate_card_price_per_unit' => 4.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-EVS-SHR10000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR EVS Storage - 10,000GB',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.2,
    'rate_card_price_per_unit' => 0.22,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 399.88,
    'rate_card_price_per_unit' => 439.87,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-EIP-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Elastic IP',
    'measurement_unit' => 'Unit Per Day',
    'description' => 'Monthly',
    'price_per_unit' => 1.0,
    'rate_card_price_per_unit' => 1.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CLIC-HBDR1-NODOTC' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Agent (per pair agent) per Month',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 128.0,
    'rate_card_price_per_unit' => 140.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 412.0,
    'rate_card_price_per_unit' => 453.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 1496.0,
    'rate_card_price_per_unit' => 1645.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-SFS-SHR-STD' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Scalable File Service (SFS)',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.43,
    'rate_card_price_per_unit' => 0.47,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-VFW-DDT-OS' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Cloud Firewall (OPNSense)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 100.0,
    'rate_card_price_per_unit' => 110.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-MM1000' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '3x Master Nodes (Cluster Size:201-1000)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 2532.3,
    'rate_card_price_per_unit' => 2785.53,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-OBS-SHR1000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR OBS Storage - 1,000GB',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.12,
    'rate_card_price_per_unit' => 0.13,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SQLSTD' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft SQL (Standard) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 802.72,
    'rate_card_price_per_unit' => 882.99,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-SM200' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '1x Master Nodes (Cluster Size:51-200)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 439.3,
    'rate_card_price_per_unit' => 483.23,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-100DR' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Cloud Server Disaster Recovery (vPLL)',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 19.0,
    'rate_card_price_per_unit' => 20.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.6XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.6xlarge.dr',
    'measurement_unit' => ' Unit ',
    'description' => 'Monthly',
    'price_per_unit' => 181.64,
    'rate_card_price_per_unit' => 199.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 326.66,
    'rate_card_price_per_unit' => 359.33,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 5056.0,
    'rate_card_price_per_unit' => 5561.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.LARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.large.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 22.18,
    'rate_card_price_per_unit' => 24.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 316.0,
    'rate_card_price_per_unit' => 347.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-BCK-SHR-SNP' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Snapshot Storage',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.2,
    'rate_card_price_per_unit' => 0.22,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-EIP-SHR-STD' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Elastic IP',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 20.0,
    'rate_card_price_per_unit' => 22.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSBS-STRG-BCK-STD' => 
  array (
    'category_name' => 'Cloud Backup',
    'category_code' => 'CSBS',
    'name' => 'Backup Disk',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.2,
    'rate_card_price_per_unit' => 0.22,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 484.36,
    'rate_card_price_per_unit' => 532.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 799.75,
    'rate_card_price_per_unit' => 879.73,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-BWS-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Bandwidth',
    'measurement_unit' => 'Mbps Per Day',
    'description' => 'Monthly',
    'price_per_unit' => 1.1,
    'rate_card_price_per_unit' => 1.21,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 2904.0,
    'rate_card_price_per_unit' => 3194.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.MICRO.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.micro.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 2.47,
    'rate_card_price_per_unit' => 2.72,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 29.57,
    'rate_card_price_per_unit' => 32.53,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-DDH-DDT-R3P.46XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.46xlarge.ddh',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 21970.3,
    'rate_card_price_per_unit' => 24167.33,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CSEC-VFW-DDTOSDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Cloud Firewall (OPNSense)',
    'measurement_unit' => 'Days',
    'description' => 'Monthly',
    'price_per_unit' => 4.0,
    'rate_card_price_per_unit' => 4.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 2528.0,
    'rate_card_price_per_unit' => 2780.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMNS-MOS-NOD-STD' => 
  array (
    'category_name' => 'Cloud Managed Service',
    'category_code' => 'CMNS',
    'name' => 'Managed Operating System',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 60.0,
    'rate_card_price_per_unit' => 66.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SRVSTD' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft Windows Server (Core Pack) - Standard',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 3.0,
    'rate_card_price_per_unit' => 3.3,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 824.0,
    'rate_card_price_per_unit' => 906.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 121.09,
    'rate_card_price_per_unit' => 133.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-10' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (1-10Mbps) + 2 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 30.0,
    'rate_card_price_per_unit' => 33.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 98.56,
    'rate_card_price_per_unit' => 108.42,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-SEEDVM.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'Cold DR - Seeding VM',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 39.4,
    'rate_card_price_per_unit' => 43.34,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 4320.0,
    'rate_card_price_per_unit' => 4752.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CPFS-PFS-MDY-1OTC' => 
  array (
    'category_name' => 'Cloud Professional Services',
    'category_code' => 'CPFS',
    'name' => 'Manday - =>1 Day',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 1500.0,
    'rate_card_price_per_unit' => 1650.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-OBS-SHR-STD' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Object Storage Service (OBS)',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.12,
    'rate_card_price_per_unit' => 0.13,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.6XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.6xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 1896.0,
    'rate_card_price_per_unit' => 2085.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 81.67,
    'rate_card_price_per_unit' => 89.84,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 394.24,
    'rate_card_price_per_unit' => 433.66,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-EVS-SHR5000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR EVS Storage - 5,000GB',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.2,
    'rate_card_price_per_unit' => 0.22,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.LARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.large',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 102.0,
    'rate_card_price_per_unit' => 112.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-ELB-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'Elastic Load Balancer',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 7.0,
    'rate_card_price_per_unit' => 7.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSBS-STRG-BCK-REPS' => 
  array (
    'category_name' => 'Cloud Backup',
    'category_code' => 'CSBS',
    'name' => 'Cloud Server Replication Service - Retention Capacity',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.2,
    'rate_card_price_per_unit' => 0.22,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SRVDC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft Windows Server (Core Pack) - Data Center',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 185.85,
    'rate_card_price_per_unit' => 204.44,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLWEBOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft SQL (Web) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 50.22,
    'rate_card_price_per_unit' => 55.24,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-10' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (1-10Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 25.0,
    'rate_card_price_per_unit' => 27.5,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 354.82,
    'rate_card_price_per_unit' => 390.3,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-ELB-SHR-STD' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Elastic Load Balancer',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 117.0,
    'rate_card_price_per_unit' => 128.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-80' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (51-80Mbps) + 8 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 23.0,
    'rate_card_price_per_unit' => 25.3,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.3XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.3xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 1572.0,
    'rate_card_price_per_unit' => 1729.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 2992.0,
    'rate_card_price_per_unit' => 3291.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-SHR-500' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Shared Bandwidth + 1 EIP (500Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 258.0,
    'rate_card_price_per_unit' => 283.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-COR-127' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'RHEL (9-127vCPU)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 41.15,
    'rate_card_price_per_unit' => 45.27,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-SM50' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '1x Master Nodes (Cluster Size:1-50)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 236.9,
    'rate_card_price_per_unit' => 260.59,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-NAT-MSHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'NAT Gateway (Medium)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 11.0,
    'rate_card_price_per_unit' => 12.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-EVS-SHR-STD' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Elastic Volume Service (EVS)',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.21,
    'rate_card_price_per_unit' => 0.23,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.SMALL' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.small',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 51.0,
    'rate_card_price_per_unit' => 56.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 24.64,
    'rate_card_price_per_unit' => 27.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.LARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.large.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 7.4,
    'rate_card_price_per_unit' => 8.14,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 197.12,
    'rate_card_price_per_unit' => 216.83,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 204.0,
    'rate_card_price_per_unit' => 224.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-DRCOR-127' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- RHEL (9-127vCPU)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 41.15,
    'rate_card_price_per_unit' => 45.27,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-MM200' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '3x Master Nodes (Cluster Size:51-200)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 1317.9,
    'rate_card_price_per_unit' => 1449.69,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLSTD' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft SQL (Standard) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 72.0,
    'rate_card_price_per_unit' => 79.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 177.41,
    'rate_card_price_per_unit' => 195.15,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-100' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (81-100Mbps) + 8 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 20.0,
    'rate_card_price_per_unit' => 22.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-USR-RDSSAL' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft Remote Desktop Services (SAL)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 35.5,
    'rate_card_price_per_unit' => 39.05,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.3XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.3xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 73.92,
    'rate_card_price_per_unit' => 81.31,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMNS-MPT-NOD-STD' => 
  array (
    'category_name' => 'Cloud Managed Service',
    'category_code' => 'CMNS',
    'name' => 'Managed Patching',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 50.0,
    'rate_card_price_per_unit' => 55.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 118.28,
    'rate_card_price_per_unit' => 130.11,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-80' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (51-80Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 20.5,
    'rate_card_price_per_unit' => 22.55,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 60.55,
    'rate_card_price_per_unit' => 66.61,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 236.55,
    'rate_card_price_per_unit' => 260.21,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-DRCOR-127OTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- RHEL (9-127vCPU)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 41.15,
    'rate_card_price_per_unit' => 45.27,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.12XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.12xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 8976.0,
    'rate_card_price_per_unit' => 9873.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMON-TIS-NOD-STD' => 
  array (
    'category_name' => 'Cloud Monitoring',
    'category_code' => 'CMON',
    'name' => 'TCS inSight vMonitoring',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 40.0,
    'rate_card_price_per_unit' => 44.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CPFS-PFS-MDY-5OTC' => 
  array (
    'category_name' => 'Cloud Professional Services',
    'category_code' => 'CPFS',
    'name' => 'Manday - =>5 Days',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 1200.0,
    'rate_card_price_per_unit' => 1320.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 4192.0,
    'rate_card_price_per_unit' => 4611.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-EIP-SHR-FOC' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Included Elastic IP (FOC)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-STRG-EVS-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Elastic Volume Service (EVS)',
    'measurement_unit' => 'GB Per Day',
    'description' => 'Monthly',
    'price_per_unit' => 0.09,
    'rate_card_price_per_unit' => 0.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.LARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.large',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 270.0,
    'rate_card_price_per_unit' => 297.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'SECT-VAS-EIP-STD' => 
  array (
    'category_name' => 'Security Services',
    'category_code' => 'SECT',
    'name' => 'Cloud Vulnerability Assessment (Per IP)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 80.0,
    'rate_card_price_per_unit' => 88.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-NAT-SHR-M' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'NAT Gateway (Medium)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 148.0,
    'rate_card_price_per_unit' => 162.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSBS-STRG-BCK-CSBSI' => 
  array (
    'category_name' => 'Cloud Backup',
    'category_code' => 'CSBS',
    'name' => 'Cloud Server Backup Service - Incremental Backup Capacity',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.2,
    'rate_card_price_per_unit' => 0.22,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-GLB-SHR-DOMAIN' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Global Server Load Balancer (GSLB)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 100.0,
    'rate_card_price_per_unit' => 110.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-50' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (31-50Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 22.0,
    'rate_card_price_per_unit' => 24.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-NAT-SHR-L' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'NAT Gateway (Large)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 294.0,
    'rate_card_price_per_unit' => 323.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 2160.0,
    'rate_card_price_per_unit' => 2376.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CSEC-VFW-DDTFGDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Cloud Firewall (Fortigate)',
    'measurement_unit' => 'Days',
    'description' => 'Monthly',
    'price_per_unit' => 38.0,
    'rate_card_price_per_unit' => 41.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-VFW-DDT-FG' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Cloud Firewall (Fortigate)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 950.0,
    'rate_card_price_per_unit' => 1045.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 524.0,
    'rate_card_price_per_unit' => 576.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-SHR-300' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Shared Bandwidth + 1 EIP (300Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 188.0,
    'rate_card_price_per_unit' => 206.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 632.0,
    'rate_card_price_per_unit' => 695.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-L2BR-SHR-INT' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'vPLL L2BR Instance',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 51.75,
    'rate_card_price_per_unit' => 56.93,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 40.84,
    'rate_card_price_per_unit' => 44.92,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-30' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (11-30Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 23.5,
    'rate_card_price_per_unit' => 25.85,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-OBS-SHR-IMG' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Image Storage',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.12,
    'rate_card_price_per_unit' => 0.13,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 44.36,
    'rate_card_price_per_unit' => 48.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-DRCOR-8' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- RHEL (1-8vCPU)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 54.84,
    'rate_card_price_per_unit' => 60.32,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-DGW-SHR-EXT' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Direct Connect Virtual Gateway',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 95.0,
    'rate_card_price_per_unit' => 104.5,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-30' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (11-30Mbps )+ AntiDDoS + 4 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 48.0,
    'rate_card_price_per_unit' => 52.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.12XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.12xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 532.23,
    'rate_card_price_per_unit' => 585.45,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSBS-STRG-BCK-CSBSF' => 
  array (
    'category_name' => 'Cloud Backup',
    'category_code' => 'CSBS',
    'name' => 'Cloud Server Backup Service - Full Backup Capacity',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.2,
    'rate_card_price_per_unit' => 0.22,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-10' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (1-10Mbps) + AntiDDoS + 2 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 50.0,
    'rate_card_price_per_unit' => 55.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.3XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.3xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 90.82,
    'rate_card_price_per_unit' => 99.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-BWD-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Bandwidth + AntiDDoS ',
    'measurement_unit' => 'Mbps Per Day',
    'description' => 'Monthly',
    'price_per_unit' => 1.9,
    'rate_card_price_per_unit' => 2.09,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 816.0,
    'rate_card_price_per_unit' => 897.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CPFS-PFS-MDY-3OTC' => 
  array (
    'category_name' => 'Cloud Professional Services',
    'category_code' => 'CPFS',
    'name' => 'Manday - =>3 Days',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 1300.0,
    'rate_card_price_per_unit' => 1430.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLWEB' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft SQL (Web) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 5.0,
    'rate_card_price_per_unit' => 5.5,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 1648.0,
    'rate_card_price_per_unit' => 1812.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 1632.0,
    'rate_card_price_per_unit' => 1795.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-RDSSALOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft Remote Desktop Services (SAL)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 35.16,
    'rate_card_price_per_unit' => 38.68,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.MICRO' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.micro',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 37.0,
    'rate_card_price_per_unit' => 40.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-50' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (31-50Mbps) + AntiDDoS + 6 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 42.0,
    'rate_card_price_per_unit' => 46.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 5161.0,
    'rate_card_price_per_unit' => 5677.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.3XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.3xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 948.0,
    'rate_card_price_per_unit' => 1042.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLSTDOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft SQL (Standard) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 795.0,
    'rate_card_price_per_unit' => 874.5,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-EDR-NOD-STD' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Anti-Virus (Panda)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 10.0,
    'rate_card_price_per_unit' => 11.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 8168.0,
    'rate_card_price_per_unit' => 8984.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-EVS-SHR1000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR EVS Storage - 1,000GB',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.21,
    'rate_card_price_per_unit' => 0.23,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 1080.0,
    'rate_card_price_per_unit' => 1188.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-50' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (31-50Mbps) + 6 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 26.0,
    'rate_card_price_per_unit' => 28.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 1264.0,
    'rate_card_price_per_unit' => 1390.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-SM1000' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '1x Master Nodes (Cluster Size:201-1000)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 844.1,
    'rate_card_price_per_unit' => 928.51,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLENTOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft SQL (Enterprise) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 2994.0,
    'rate_card_price_per_unit' => 3293.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SRVSTDOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft Windows Server (Core Pack) - Standard',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 26.78,
    'rate_card_price_per_unit' => 29.46,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.12XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.12xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 599.81,
    'rate_card_price_per_unit' => 659.79,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-OBS-SHR5000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR OBS Storage - 5,000GB',
    'measurement_unit' => 'GB',
    'description' => 'Monthly',
    'price_per_unit' => 0.11,
    'rate_card_price_per_unit' => 0.12,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 3264.0,
    'rate_card_price_per_unit' => 3590.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 2529.0,
    'rate_card_price_per_unit' => 2781.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 1048.0,
    'rate_card_price_per_unit' => 1152.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 59.14,
    'rate_card_price_per_unit' => 65.05,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SRVSTD' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft Windows Server (Core Pack) - Standard',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 27.04,
    'rate_card_price_per_unit' => 29.74,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLENT' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft SQL (Enterprise) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 271.0,
    'rate_card_price_per_unit' => 298.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-COR-8' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'RHEL (1-8vCPU)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 54.84,
    'rate_card_price_per_unit' => 60.32,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 3657.0,
    'rate_card_price_per_unit' => 4022.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-SHR-100' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Shared Bandwidth + 1 EIP (100Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 128.0,
    'rate_card_price_per_unit' => 140.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-L2BR-SHR-EXT' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'L2BR instance',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 91.0,
    'rate_card_price_per_unit' => 100.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.LARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.large.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 12.32,
    'rate_card_price_per_unit' => 13.55,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-80' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (51-80Mbps) + AntiDDoS + 8 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 39.0,
    'rate_card_price_per_unit' => 42.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SQLWEB' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft SQL (Web) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 50.22,
    'rate_card_price_per_unit' => 55.24,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 11968.0,
    'rate_card_price_per_unit' => 13164.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 88.71,
    'rate_card_price_per_unit' => 97.58,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-DRCOR-8OTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- RHEL (1-8vCPU)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 54.84,
    'rate_card_price_per_unit' => 60.32,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-100' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (81-100Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 19.0,
    'rate_card_price_per_unit' => 20.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-NAT-XLSHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'NAT Gateway (Extra-Large)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 57.0,
    'rate_card_price_per_unit' => 62.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 5984.0,
    'rate_card_price_per_unit' => 6582.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-NAT-LSHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'NAT Gateway (Large)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 20.0,
    'rate_card_price_per_unit' => 22.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMNS-MBR-NOD-STD' => 
  array (
    'category_name' => 'Cloud Managed Service',
    'category_code' => 'CMNS',
    'name' => 'Managed Backup and Restore',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 60.0,
    'rate_card_price_per_unit' => 66.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CPFS-PFS-MDY-0.5OTC' => 
  array (
    'category_name' => 'Cloud Professional Services',
    'category_code' => 'CPFS',
    'name' => 'Manday - 0.5Days',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 800.0,
    'rate_card_price_per_unit' => 880.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 748.0,
    'rate_card_price_per_unit' => 822.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-WAF-SHR-HA' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Cloud Shared WAF (Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 60.0,
    'rate_card_price_per_unit' => 66.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 199.94,
    'rate_card_price_per_unit' => 219.93,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 8384.0,
    'rate_card_price_per_unit' => 9222.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CLIC-HBDR50-NOD' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Agent (>50 pair agent)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 92.48,
    'rate_card_price_per_unit' => 101.73,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 540.0,
    'rate_card_price_per_unit' => 594.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.SMALL.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.small.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 3.7,
    'rate_card_price_per_unit' => 4.07,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 2096.0,
    'rate_card_price_per_unit' => 2305.6,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-NAT-SSHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'NAT Gateway (Small)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 2.0,
    'rate_card_price_per_unit' => 2.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SQLENT' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft SQL (Enterprise) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 2993.17,
    'rate_card_price_per_unit' => 3292.49,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 49.99,
    'rate_card_price_per_unit' => 54.99,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.LARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.large',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 158.0,
    'rate_card_price_per_unit' => 173.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SRVDCOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft Windows Server (Core Pack) - Data Center',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 185.85,
    'rate_card_price_per_unit' => 204.44,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SRVDC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft Windows Server (Core Pack) - Data Center',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 185.85,
    'rate_card_price_per_unit' => 204.44,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 8640.0,
    'rate_card_price_per_unit' => 9504.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CLIC-CSDR-NOD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'Cloud Server Disaster Recovery Replication',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 28.0,
    'rate_card_price_per_unit' => 30.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-100' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (81-100Mbps) + AntiDDoS + 8 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => 'Monthly',
    'price_per_unit' => 32.0,
    'rate_card_price_per_unit' => 35.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CLIC-HBDR20-NOD' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Agent (>20 pair agent)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 108.8,
    'rate_card_price_per_unit' => 119.68,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 99.97,
    'rate_card_price_per_unit' => 109.97,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CLIC-HBDR1-NOD' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Agent (per pair agent)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 128.0,
    'rate_card_price_per_unit' => 140.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CMPT-ECS-C3.LARGE' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'MPDR Replication Proxy',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 102.0,
    'rate_card_price_per_unit' => 112.2,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 242.18,
    'rate_card_price_per_unit' => 266.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CMNS-MDR-NODDAY' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Cloud Server Disaster Recovery Managed Service - Per Day',
    'measurement_unit' => 'VM',
    'description' => 'Monthly',
    'price_per_unit' => 10.0,
    'rate_card_price_per_unit' => 11.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-NAT-SHR-XL' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'NAT Gateway (Extra-Large)',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 879.0,
    'rate_card_price_per_unit' => 966.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMNS-MDR-NOD-STD' => 
  array (
    'category_name' => 'Cloud Managed Service',
    'category_code' => 'CMNS',
    'name' => 'Managed DR',
    'measurement_unit' => 'Unit',
    'description' => 'Monthly',
    'price_per_unit' => 50.0,
    'rate_card_price_per_unit' => 55.0,
    'transfer_price_per_unit' => 0.0,
  ),
  '_catalog' => 
  array (
    'id' => '01999f09-9a41-70a5-bf39-bb2f3e56a2f8',
    'version_code' => 'v1.1.0',
    'version_name' => 'v1.1.0',
    'effective_from' => '2025-09-01',
    'effective_to' => NULL,
    'is_current' => true,
    'generated_at' => '2025-10-01 17:12:05',
  ),
);
