<?php

return array (
  'CMDR-NAT-DRD-S' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'NAT GATEWAY (Small)',
    'measurement_unit' => 'Unit',
    'description' => 'NAT GATEWAY (Small)',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 29.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-EIP-SHR-DAY' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Network (DR Elastic IP)',
    'measurement_unit' => 'Unit',
    'description' => '(Per Day) DR Elastic IP',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 41.8,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-NAT-SHR-XL' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'NAT Gateway (Extra-Large) ',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CPFS-PFS-MDY-3OTC' => 
  array (
    'category_name' => 'Cloud Professional Services',
    'category_code' => 'CPFS',
    'name' => 'Manday - =>3 Days',
    'measurement_unit' => 'Day',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CLIC-HBDR10-NOD' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Agent (>10 pair agent)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-EIP-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Elastic IP',
    'measurement_unit' => 'Unit Per Day',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-30' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (11-30Mbps )+ AntiDDoS + 4 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.6XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.6xlarge.dr',
    'measurement_unit' => ' Unit ',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-80' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (51-80Mbps) + 8 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-EVS-SHR1000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR EVS Storage - 1,000GB',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-SHR-100' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Shared Bandwidth + 1 EIP (100Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'SECT-VAS-EIP-STD' => 
  array (
    'category_name' => 'Security Services',
    'category_code' => 'SECT',
    'name' => 'Cloud Vulnerability Assessment (Per IP)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMDR-NAT-DRD-M' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'NAT GATEWAY (Medium)',
    'measurement_unit' => 'Unit',
    'description' => 'NAT GATEWAY (Medium)',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 42.9,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-DDH-DDT-R3P.46XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.46xlarge.ddh',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SQLENT' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft SQL (Enterprise) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-NAT-XLSHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'NAT Gateway (Extra-Large)',
    'measurement_unit' => 'Unit',
    'description' => 'Public NAT gateways translate private IP addresses into EIPs, and are used by cloud servers in a VPC for secure, cost-effective Internet access. Private NAT gateways translate between private IP addresses, and are used between VPCs or your VPC and on-premises data center to keep legacy networks running after cloud migration. Maximum SNAT Connections = 1,000,000; Bandwidth=20Gbps; PPS=2,000,000',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMNS-MBR-NOD-STD' => 
  array (
    'category_name' => 'Cloud Managed Service',
    'category_code' => 'CMNS',
    'name' => 'Managed Backup and Restore',
    'measurement_unit' => 'VM',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-MPDR-NOD-HBDR1' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Agent (per pair agent)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.LARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.large',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMNS-MDR-NOD-STD' => 
  array (
    'category_name' => 'Cloud Managed Service',
    'category_code' => 'CMNS',
    'name' => 'Managed DR',
    'measurement_unit' => 'VM',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLWEB' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft SQL (Web) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-VFW-DDT-FGDAY' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Additional Services-Security',
    'measurement_unit' => 'Unit',
    'description' => '(Per Day) DR Cloud Firewall Fortigate',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 4.4,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SRVSTDOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft Windows Server (Core Pack) - Standard',
    'measurement_unit' => ' Unit ',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-DRCOR-8OTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- RHEL (1-8vCPU)',
    'measurement_unit' => ' Unit ',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-30' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (11-30Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-COR-8' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'RHEL (1-8vCPU)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-EVS-SHR5000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR EVS Storage - 5,000GB',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMDR-ELB-DRD-STD' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Elastic Load Balancer',
    'measurement_unit' => 'Unit',
    'description' => 'Elastic Load Balancer',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 62.7,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-100DR' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Cloud Server Disaster Recovery (vPLL)',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.12XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.12xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-MPDR-NOD-HBDR20' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Agent (>10 pair agent)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-SFS-SHR-STD' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Scalable File Service (SFS)',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-80' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (51-80Mbps) + AntiDDoS + 8 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.LARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.large.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SRVDC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft Windows Server (Core Pack) - Data Center',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLENT' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft SQL (Enterprise) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CMPT-ECS-C3.LARGE' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'MPDR Replication Proxy',
    'measurement_unit' => 'Unit',
    'description' => '-',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMNS-MOS-NOD-STD' => 
  array (
    'category_name' => 'Cloud Managed Service',
    'category_code' => 'CMNS',
    'name' => 'Managed Operating System',
    'measurement_unit' => 'VM',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-OBS-SHR5000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR OBS Storage - 5,000GB',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-VFW-DDT-OSDAY' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Additional Services-Security',
    'measurement_unit' => 'Unit',
    'description' => '(Per Day) DR Cloud Firewall OPNSense',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.LARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.large',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CPFS-PFS-MDY-0.5OTC' => 
  array (
    'category_name' => 'Cloud Professional Services',
    'category_code' => 'CPFS',
    'name' => 'Manday - 0.5Days',
    'measurement_unit' => 'Day',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMDR-NAT-DRD-XL' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'NAT GATEWAY (Extra-Large)',
    'measurement_unit' => 'Unit',
    'description' => 'NAT GATEWAY (Extra-Large)',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 3630.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-EVS-SHR-STD' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Elastic Volume Service (EVS)',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-50' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (31-50Mbps) + AntiDDoS + 6 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-80' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (51-80Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-ELB-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'Elastic Load Balancer',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-SEEDVM.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'Cold DR - Seeding VM',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-ELB-SHR-STD' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Elastic Load Balancer',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3P.6XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.6xlarge',
    'measurement_unit' => ' Unit ',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.SMALL' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.small',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-RDSSAL' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft Remote Desktop Services (SAL)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-RDSSALOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft Remote Desktop Services (SAL)',
    'measurement_unit' => ' Unit ',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-SHR-300' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Shared Bandwidth + 1 EIP (300Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CMNS-MDR-NODDAY' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Cloud Server Disaster Recovery Managed Service - Per Day',
    'measurement_unit' => 'VM',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMNS-MPT-NOD-STD' => 
  array (
    'category_name' => 'Cloud Managed Service',
    'category_code' => 'CMNS',
    'name' => 'Managed Patching',
    'measurement_unit' => 'VM',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMON-TIS-NOD-STD' => 
  array (
    'category_name' => 'Cloud Monitoring',
    'category_code' => 'CMON',
    'name' => 'TCS inSight vMonitoring',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.MICRO.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.micro.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CLIC-HBDR1-NOD' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Agent (per pair agent)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-EIP-SHR-FOC' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Included Elastic IP (FOC)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.12XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.12xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-BWS-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Bandwidth',
    'measurement_unit' => 'Mbps Per Day',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-MM1000' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '3x Master Nodes (Cluster Size:201-1000)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLSTDOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft SQL (Standard) (Core Pack)',
    'measurement_unit' => ' Unit ',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CLIC-CSDR-NOD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'Cloud Server Disaster Recovery Replication',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-10' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (1-10Mbps) + 2 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-MM50' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '3x Master Nodes (Cluster Size:1-50)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-NAT-SSHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'NAT Gateway (Small)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-SHR-DAY' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Network (DR Bandwidth)',
    'measurement_unit' => 'Mbps',
    'description' => '(Per Day) DR Bandwidth',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 2.09,
    'transfer_price_per_unit' => 1.0,
  ),
  'CLIC-WIN-COR-SQLWEB' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft SQL (Web) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.3XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.3xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-OBS-SHR-IMG' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Image Storage',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-OBS-SHR-STD' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Object Storage Service (OBS)',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-SHR-DAY' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Network (DR Bandwidth + Anti-DDoS)',
    'measurement_unit' => 'Mbps',
    'description' => '(Per Day) DR Bandwidth + Anti-DDoS',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 1.1,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.LARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.large.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMDR-NAT-DRD-L' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'NAT GATEWAY (Large)',
    'measurement_unit' => 'Unit',
    'description' => 'NAT GATEWAY (Large)',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 957.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-NAT-MSHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'NAT Gateway (Medium)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-EVS-SHR10000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR EVS Storage - 10,000GB',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.6XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.6xlarge',
    'measurement_unit' => ' Unit ',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLWEBOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft SQL (Web) (Core Pack)',
    'measurement_unit' => ' Unit ',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-MPDR-NOD-HBDR1OTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Agent (per pair agent)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-DRCOR-127OTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- RHEL (9-127vCPU)',
    'measurement_unit' => ' Unit ',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-30' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (11-30Mbps) + 4 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-L2BR-SHR-EXT' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'L2BR instance',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-DRCOR-8' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- RHEL (1-8vCPU)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CSEC-VFW-DDTOSDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Cloud Firewall (OPNSense)',
    'measurement_unit' => 'Days',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLENTOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft SQL (Enterprise) (Core Pack)',
    'measurement_unit' => ' Unit ',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.SMALL.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.small.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.3XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.3xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-GLB-SHR-DOMAIN' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Global Server Load Balancer (GSLB)',
    'measurement_unit' => 'Unit',
    'description' => 'Global Server Load Balancer provided by TT dotcom In house to address load balancing across multiple regions. Calculated based on per domain, where each domain is limited to 1000QPS',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-COR-127' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'RHEL (9-127vCPU)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-EDR-NOD-STD' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Anti-Virus (Panda)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.LARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.large',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-R3P.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3p.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.3XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.3xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-50' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (31-50Mbps) + 6 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SQLSTD' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft SQL (Standard) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CLIC-HBDR50-NOD' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Agent (>50 pair agent)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-C3.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-SM200' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '1x Master Nodes (Cluster Size:51-200)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-NAT-SHR-L' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'NAT Gateway (Large) ',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-100' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (81-100Mbps) + AntiDDoS + 8 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-WAF-SHR-HA' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Cloud Shared WAF (Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-OBS-SHR10000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR OBS Storage - 10,000GB',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSBS-STRG-BCK-STD' => 
  array (
    'category_name' => 'Cloud Backup',
    'category_code' => 'CSBS',
    'name' => 'Backup Disk',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-USR-RDSSAL' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft Remote Desktop Services (SAL)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-STRG-OBS-SHR1000' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Backup and DR OBS Storage - 1,000GB',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3.2XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3.2xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-DGW-SHR-EXT' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Direct Connect Virtual Gateway',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-STRG-EVS-SHRSTD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'Cloud Server Disaster Recovery Storage',
    'measurement_unit' => 'GB',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-RHL-DRCOR-127' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- RHEL (9-127vCPU)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-STRG-EVS-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Elastic Volume Service (EVS)',
    'measurement_unit' => 'GB Per Day',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.MICRO' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.micro',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-NAT-LSHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'NAT Gateway (Large)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-SM1000' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '1x Master Nodes (Cluster Size:201-1000)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-COR-SRVSTD' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'Microsoft Windows Server (Core Pack) - Standard',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.3XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.3xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CNET-BWD-SHRDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Bandwidth + AntiDDoS ',
    'measurement_unit' => 'Mbps Per Day',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHG-M3GNT4.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3gnt4.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CPFS-PFS-MDY-1OTC' => 
  array (
    'category_name' => 'Cloud Professional Services',
    'category_code' => 'CPFS',
    'name' => 'Manday - =>1 Day',
    'measurement_unit' => 'Day',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-MM200' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '3x Master Nodes (Cluster Size:51-200)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-100' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (81-100Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-C3P.4XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'c3p.4xlarge',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-CIA-100' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (81-100Mbps) + 8 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SQLSTD' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft SQL (Standard) (Core Pack)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3.12XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3.12xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSBS-STRG-BCK-CSBSF' => 
  array (
    'category_name' => 'Cloud Backup',
    'category_code' => 'CSBS',
    'name' => 'Cloud Server Backup Service - Full Backup Capacity',
    'measurement_unit' => 'GB',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-EIP-SHR-STD' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Elastic IP',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHP-M3P.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3p.xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-L2BR-SHR-INT' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'vPLL L2BR Instance',
    'measurement_unit' => 'Pair',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSBS-STRG-BCK-CSBSI' => 
  array (
    'category_name' => 'Cloud Backup',
    'category_code' => 'CSBS',
    'name' => 'Cloud Server Backup Service - Incremental Backup Capacity',
    'measurement_unit' => 'GB',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-NAT-SHR-M' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'NAT Gateway (Medium) ',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-VFW-DDT-OS' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Cloud Firewall (OPNSense)',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-M3.8XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'm3.8xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-M3P.4XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'm3p.4xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CPFS-PFS-MDY-5OTC' => 
  array (
    'category_name' => 'Cloud Professional Services',
    'category_code' => 'CPFS',
    'name' => 'Manday - =>5 Days',
    'measurement_unit' => 'Day',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.LARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.large.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'MPDR-CLIC-HBDR1-NODOTC' => 
  array (
    'category_name' => 'Multi-Platform DRaaS',
    'category_code' => 'MPDR',
    'name' => 'Agent (per pair agent) per Month',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSBS-STRG-BCK-REPS' => 
  array (
    'category_name' => 'Cloud Backup',
    'category_code' => 'CSBS',
    'name' => 'Cloud Server Replication Service - Retention Capacity',
    'measurement_unit' => 'GB',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SRVDC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft Windows Server (Core Pack) - Data Center',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWS-SHR-500' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Shared Bandwidth + 1 EIP (500Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SRVSTD' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR Per Month- Microsoft Windows Server (Core Pack) - Standard',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CSEC-VFW-DDTFGDRD' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'DR Cloud Firewall (Fortigate)',
    'measurement_unit' => 'Days',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.2XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.2xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSTG-BCK-SHR-STD' => 
  array (
    'category_name' => 'Storage',
    'category_code' => 'CSTG',
    'name' => 'Snapshot Storage',
    'measurement_unit' => 'GB',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CLIC-WIN-DRCOR-SRVDCOTC' => 
  array (
    'category_name' => 'Licenses',
    'category_code' => 'CLIC',
    'name' => 'DR OTC- Microsoft Windows Server (Core Pack) - Data Center',
    'measurement_unit' => ' Unit ',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-50' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (31-50Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-PLL-SHR-10' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Virtual Private Leased Line (vPLL) (1-10Mbps)',
    'measurement_unit' => 'Mbps',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-NAT-SHR-S' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'NAT Gateway (Small) ',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-R3P.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'r3p.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.12XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.12xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-ECS-SHR-R3.16XLARGE' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => 'r3.16xlarge',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CSEC-VFW-DDT-FG' => 
  array (
    'category_name' => 'Cloud Security',
    'category_code' => 'CSEC',
    'name' => 'Cloud Firewall (Fortigate)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3P.8XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3p.8xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CMPT-CCE-SHR-SM50' => 
  array (
    'category_name' => 'Compute',
    'category_code' => 'CMPT',
    'name' => '1x Master Nodes (Cluster Size:1-50)',
    'measurement_unit' => 'Unit',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CDRV-CMPT-ECS-C3.16XLARGE.DR' => 
  array (
    'category_name' => 'Cloud Disaster Recovery',
    'category_code' => 'CDRV',
    'name' => 'c3.16xlarge.dr',
    'measurement_unit' => 'Unit',
    'description' => '',
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
  'CNET-BWD-CIA-10' => 
  array (
    'category_name' => 'Cloud Network',
    'category_code' => 'CNET',
    'name' => 'Bandwidth (1-10Mbps) + AntiDDoS + 2 Elastic IP',
    'measurement_unit' => 'Mbps',
    'description' => NULL,
    'price_per_unit' => 0.0,
    'rate_card_price_per_unit' => 0.0,
    'transfer_price_per_unit' => 0.0,
  ),
);
